schema: "https://myorg.com/schemas/pipeline/v1"
pipeline:
  name: "globalise_etl_pipeline"
  description: "Reads data from Django API"
  schedule: "@daily"
#  params:
#    location: ""  # Default value

  tasks:
    fetch_api_with_page:
      type: "FetchAPIWithPageOperator"
      table_name: "location"
      distance: 3
      output_trace: "ttl"
      output_store: "ttl"
#    test_comunica:
#      type: "EmitTTLOperator"
#      input_file_path: "http://nginx/locations.ttl"
#      output_store: "ttl"
#      output_trace: "ttl"

    save_file_ttl:
      type: "SaveFileTTLOperator"
      output_trace: "ttl"
      output_store: "ttl"

    run_sparql_comunica:
      type: "RunSparqlComunicaOperator"
      docker_image: "comunica/query-sparql"
      docker_network: "traefik-public"
      docker_rdf_file: "http://nginx/output.ttl"
      docker_output_format: "text/csv"
      output_trace: "csv"
      output_store: "csv"
#      query: "/tmp/query.sparql"
      query: "
      select * 
where {
?location a <http://example.globalise.nl/temp/location>;
   	<http://example.globalise.nl/temp/location/_label> ?_label;
    <http://example.globalise.nl/temp/location/comments> ?comments;
    <http://example.globalise.nl/temp/location/coord_certainty> ?coord_certainty;
    <http://example.globalise.nl/temp/location/glob_id> ?glob_id;
    <http://example.globalise.nl/temp/location/latitude> ?latitude;
    <http://example.globalise.nl/temp/location/longitude> ?longitude;
    <http://example.globalise.nl/temp/location/point> ?point.

OPTIONAL {    
	?location <http://example.globalise.nl/temp/location/location2coordsource> ?_coordsource.
	?_coordsource <http://example.globalise.nl/temp/source/page_no> ?coordsource_page_no;
    	<http://example.globalise.nl/temp/source/zotero_url> ?coordsource_zotero_url.
}
    
OPTIONAL {
    ?location <http://example.globalise.nl/temp/location/location2source> ?_source.
	?_source <http://example.globalise.nl/temp/source/page_no> ?source_page_no;
    	<http://example.globalise.nl/temp/source/zotero_url> ?source_zotero_url.
}
    
OPTIONAL {
    ?_l <http://example.globalise.nl/temp/label/locationlabel> ?location;
        <http://example.globalise.nl/temp/label/label> ?label;
        <http://example.globalise.nl/temp/label/type> ?label_type.
}
} limit 100
"

    csv_iterator:
      type: "CSVIteratorOperator"
      output_trace: "csv"
      tasks:
        json_to_csv_row:
          type: "JSONToCSVOperator"
        xslt_row:
          type: "XSLTTransformOperator"
          xslt_file: ""
        print_csv_row:
          type: "PrintOperator"
